# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster
WORKDIR /endzone
COPY requirements.txt requirements.txt
COPY dependencies /dependencies

RUN pip3 install -r requirements.txt

RUN apt-get update && apt-get install -y \
    wkhtmltopdf

EXPOSE 5000
COPY . .
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]